name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: ERC20 - intall dependencies
        run: yarn
        working-directory: erc20
      - name: ERC20 build
        run: yarn build
        working-directory: erc20
      - name: ERC20 run tests
        run: yarn test
        working-directory: erc20
      - name: Staking contract - install dependencies
        run: yarn
        working-directory: staking
      - name: Staking contract build
        run: yarn build
        working-directory: staking
      - name: Integration - install dependencies
        run: yarn
        working-directory: integration
      - name: Integration tests
        run: yarn test
        working-directory: integration